//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_GUI_C {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_EN() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C_GUI_C.en-EN", typeof(en_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ballistic Calculator.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Kind of Bullets.
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Kind of Cartridges.
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Options.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Languages.
        /// </summary>
        internal static string _21 {
            get {
                return ResourceManager.GetString("21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visual Mode.
        /// </summary>
        internal static string _22 {
            get {
                return ResourceManager.GetString("22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abbreviations.
        /// </summary>
        internal static string abb {
            get {
                return ResourceManager.GetString("abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Armour Piercing.
        /// </summary>
        internal static string ap {
            get {
                return ResourceManager.GetString("ap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Correction Value: .
        /// </summary>
        internal static string bc_corr {
            get {
                return ResourceManager.GetString("bc_corr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ballistic Coefficient.
        /// </summary>
        internal static string bc1 {
            get {
                return ResourceManager.GetString("bc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Weight .
        /// </summary>
        internal static string bc2 {
            get {
                return ResourceManager.GetString("bc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Shape Coefficient.
        /// </summary>
        internal static string bc3 {
            get {
                return ResourceManager.GetString("bc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Diameter.
        /// </summary>
        internal static string bc4 {
            get {
                return ResourceManager.GetString("bc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BC Value:.
        /// </summary>
        internal static string bcval {
            get {
                return ResourceManager.GetString("bcval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Belted.
        /// </summary>
        internal static string belted {
            get {
                return ResourceManager.GetString("belted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Calculate.
        /// </summary>
        internal static string button {
            get {
                return ResourceManager.GetString("button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a One or more field are &apos;0&apos;.
        /// </summary>
        internal static string camp0 {
            get {
                return ResourceManager.GetString("camp0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Density .
        /// </summary>
        internal static string cdf1 {
            get {
                return ResourceManager.GetString("cdf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Shape Coef. Value:.
        /// </summary>
        internal static string cdf2 {
            get {
                return ResourceManager.GetString("cdf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Center Fire.
        /// </summary>
        internal static string centf {
            get {
                return ResourceManager.GetString("centf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clear.
        /// </summary>
        internal static string clearB {
            get {
                return ResourceManager.GetString("clearB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Drag Coeff..
        /// </summary>
        internal static string coax {
            get {
                return ResourceManager.GetString("coax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Comparator.
        /// </summary>
        internal static string comp {
            get {
                return ResourceManager.GetString("comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Converter.
        /// </summary>
        internal static string Conv {
            get {
                return ResourceManager.GetString("Conv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Distance.
        /// </summary>
        internal static string cx1 {
            get {
                return ResourceManager.GetString("cx1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Drag Coeff. Value:.
        /// </summary>
        internal static string cxval {
            get {
                return ResourceManager.GetString("cxval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Explosive.
        /// </summary>
        internal static string Ex {
            get {
                return ResourceManager.GetString("Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Env. Fact. Value:.
        /// </summary>
        internal static string faval {
            get {
                return ResourceManager.GetString("faval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fill all values.
        /// </summary>
        internal static string fill {
            get {
                return ResourceManager.GetString("fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Shapes.
        /// </summary>
        internal static string form {
            get {
                return ResourceManager.GetString("form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Frangible.
        /// </summary>
        internal static string Fra {
            get {
                return ResourceManager.GetString("Fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hollow Point.
        /// </summary>
        internal static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a How to Use.
        /// </summary>
        internal static string htu {
            get {
                return ResourceManager.GetString("htu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Large Pistol Primer.
        /// </summary>
        internal static string id_10 {
            get {
                return ResourceManager.GetString("id_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Small Rifle Primer.
        /// </summary>
        internal static string id_11 {
            get {
                return ResourceManager.GetString("id_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Large Rifle Primer.
        /// </summary>
        internal static string id_12 {
            get {
                return ResourceManager.GetString("id_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rimfire.
        /// </summary>
        internal static string id_13 {
            get {
                return ResourceManager.GetString("id_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 8mm Primer.
        /// </summary>
        internal static string id_14 {
            get {
                return ResourceManager.GetString("id_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Shotshell Primer.
        /// </summary>
        internal static string id_15 {
            get {
                return ResourceManager.GetString("id_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Small Pistol Primer.
        /// </summary>
        internal static string id_9 {
            get {
                return ResourceManager.GetString("id_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ø Bullet:.
        /// </summary>
        internal static string id1 {
            get {
                return ResourceManager.GetString("id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Primer:.
        /// </summary>
        internal static string id10 {
            get {
                return ResourceManager.GetString("id10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ø Neck:.
        /// </summary>
        internal static string id2 {
            get {
                return ResourceManager.GetString("id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ø Shoulder:.
        /// </summary>
        internal static string id3 {
            get {
                return ResourceManager.GetString("id3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ø Base:.
        /// </summary>
        internal static string id4 {
            get {
                return ResourceManager.GetString("id4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ø Rim:.
        /// </summary>
        internal static string id5 {
            get {
                return ResourceManager.GetString("id5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rim Thickness:.
        /// </summary>
        internal static string id6 {
            get {
                return ResourceManager.GetString("id6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Case Length:.
        /// </summary>
        internal static string id7 {
            get {
                return ResourceManager.GetString("id7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Overall Length:.
        /// </summary>
        internal static string id8 {
            get {
                return ResourceManager.GetString("id8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Case Capacity:.
        /// </summary>
        internal static string id9 {
            get {
                return ResourceManager.GetString("id9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incendiary.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Define if use the imperial or metric measures.
        /// </summary>
        internal static string in_mm {
            get {
                return ResourceManager.GetString("in-mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Jacketed.
        /// </summary>
        internal static string Jacketed {
            get {
                return ResourceManager.GetString("Jacketed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Length of ogive.
        /// </summary>
        internal static string L {
            get {
                return ResourceManager.GetString("L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Caliber of Ogive.
        /// </summary>
        internal static string N {
            get {
                return ResourceManager.GetString("N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fill all boxes.
        /// </summary>
        internal static string novalue {
            get {
                return ResourceManager.GetString("novalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Others.
        /// </summary>
        internal static string oth {
            get {
                return ResourceManager.GetString("oth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pistols.
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rifles.
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rebated Rim.
        /// </summary>
        internal static string rebrim {
            get {
                return ResourceManager.GetString("rebrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rimless.
        /// </summary>
        internal static string rimless {
            get {
                return ResourceManager.GetString("rimless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rimmed.
        /// </summary>
        internal static string rimmed {
            get {
                return ResourceManager.GetString("rimmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Shotguns.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Semi-Rimmed.
        /// </summary>
        internal static string semir {
            get {
                return ResourceManager.GetString("semir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Section (mm2).
        /// </summary>
        internal static string sez {
            get {
                return ResourceManager.GetString("sez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Some measurements are indicative and not exactly the same as real measurements..
        /// </summary>
        internal static string timg {
            get {
                return ResourceManager.GetString("timg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select &quot;g&quot; for decimal measures (g/mm2) or &quot;gr&quot; for imperial measures (lbs/in2).
        /// </summary>
        internal static string tool1 {
            get {
                return ResourceManager.GetString("tool1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tracer.
        /// </summary>
        internal static string Tra {
            get {
                return ResourceManager.GetString("Tra", resourceCulture);
            }
        }
    }
}
