//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_GUI_C {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr_FR() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C_GUI_C.fr_FR", typeof(fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ouvrir.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Calculatrice Balistique.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type de Balles.
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type de Cartouches.
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Options.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Langues.
        /// </summary>
        internal static string _21 {
            get {
                return ResourceManager.GetString("21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mode Visuel.
        /// </summary>
        internal static string _22 {
            get {
                return ResourceManager.GetString("22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abréviations.
        /// </summary>
        internal static string abb {
            get {
                return ResourceManager.GetString("abb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Balles Perforantes.
        /// </summary>
        internal static string ap {
            get {
                return ResourceManager.GetString("ap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valeur de Correction:.
        /// </summary>
        internal static string bc_corr {
            get {
                return ResourceManager.GetString("bc_corr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coefficient Balistique.
        /// </summary>
        internal static string bc1 {
            get {
                return ResourceManager.GetString("bc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Poids.
        /// </summary>
        internal static string bc2 {
            get {
                return ResourceManager.GetString("bc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coefficient de Forme.
        /// </summary>
        internal static string bc3 {
            get {
                return ResourceManager.GetString("bc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Diamètre.
        /// </summary>
        internal static string bc4 {
            get {
                return ResourceManager.GetString("bc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valeur CD:.
        /// </summary>
        internal static string bcval {
            get {
                return ResourceManager.GetString("bcval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ceinture.
        /// </summary>
        internal static string belted {
            get {
                return ResourceManager.GetString("belted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Calculer.
        /// </summary>
        internal static string button {
            get {
                return ResourceManager.GetString("button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Un ou plusieurs champs sont «0».
        /// </summary>
        internal static string camp0 {
            get {
                return ResourceManager.GetString("camp0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Densité.
        /// </summary>
        internal static string cdf1 {
            get {
                return ResourceManager.GetString("cdf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Shape Coef. Value:.
        /// </summary>
        internal static string cdf2 {
            get {
                return ResourceManager.GetString("cdf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Percussion Centrale.
        /// </summary>
        internal static string centf {
            get {
                return ResourceManager.GetString("centf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nettoyer.
        /// </summary>
        internal static string clearB {
            get {
                return ResourceManager.GetString("clearB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coeff. de Traînée.
        /// </summary>
        internal static string coax {
            get {
                return ResourceManager.GetString("coax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Convertisseur.
        /// </summary>
        internal static string Conv {
            get {
                return ResourceManager.GetString("Conv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Distance.
        /// </summary>
        internal static string cx1 {
            get {
                return ResourceManager.GetString("cx1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valeur du Coeff. de traînée:.
        /// </summary>
        internal static string cxval {
            get {
                return ResourceManager.GetString("cxval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Explosif.
        /// </summary>
        internal static string Ex {
            get {
                return ResourceManager.GetString("Ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valeur du Facteur Ambiant:.
        /// </summary>
        internal static string faval {
            get {
                return ResourceManager.GetString("faval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remplissez toutes les valeurs.
        /// </summary>
        internal static string fill {
            get {
                return ResourceManager.GetString("fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Formes.
        /// </summary>
        internal static string form {
            get {
                return ResourceManager.GetString("form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Frangible.
        /// </summary>
        internal static string Fra {
            get {
                return ResourceManager.GetString("Fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tête Creuse.
        /// </summary>
        internal static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Comment utiliser.
        /// </summary>
        internal static string htu {
            get {
                return ResourceManager.GetString("htu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Amorce Large Pistol.
        /// </summary>
        internal static string id_10 {
            get {
                return ResourceManager.GetString("id_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Amorce Small Rifle.
        /// </summary>
        internal static string id_11 {
            get {
                return ResourceManager.GetString("id_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Amorce Large Rifle.
        /// </summary>
        internal static string id_12 {
            get {
                return ResourceManager.GetString("id_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Percussion Annulaire.
        /// </summary>
        internal static string id_13 {
            get {
                return ResourceManager.GetString("id_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Amorce 8mm.
        /// </summary>
        internal static string id_14 {
            get {
                return ResourceManager.GetString("id_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Amorce Shotshell.
        /// </summary>
        internal static string id_15 {
            get {
                return ResourceManager.GetString("id_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Amorce Small Pistol.
        /// </summary>
        internal static string id_9 {
            get {
                return ResourceManager.GetString("id_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ø Projectile:.
        /// </summary>
        internal static string id1 {
            get {
                return ResourceManager.GetString("id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Amorce:.
        /// </summary>
        internal static string id10 {
            get {
                return ResourceManager.GetString("id10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ø Collet:.
        /// </summary>
        internal static string id2 {
            get {
                return ResourceManager.GetString("id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ø Còne d&apos;appui:.
        /// </summary>
        internal static string id3 {
            get {
                return ResourceManager.GetString("id3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ø Culot:.
        /// </summary>
        internal static string id4 {
            get {
                return ResourceManager.GetString("id4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ø Jante:.
        /// </summary>
        internal static string id5 {
            get {
                return ResourceManager.GetString("id5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Épaisseur de jante:.
        /// </summary>
        internal static string id6 {
            get {
                return ResourceManager.GetString("id6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Longueur de Douille:.
        /// </summary>
        internal static string id7 {
            get {
                return ResourceManager.GetString("id7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Longueur de la Cartouche:.
        /// </summary>
        internal static string id8 {
            get {
                return ResourceManager.GetString("id8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Étui Capacitance:.
        /// </summary>
        internal static string id9 {
            get {
                return ResourceManager.GetString("id9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Incendiaire.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Define if use the imperial or metric measures.
        /// </summary>
        internal static string in_mm {
            get {
                return ResourceManager.GetString("in-mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Balle Chemisée.
        /// </summary>
        internal static string Jacketed {
            get {
                return ResourceManager.GetString("Jacketed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remplissez toutes les cases.
        /// </summary>
        internal static string novalue {
            get {
                return ResourceManager.GetString("novalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autres.
        /// </summary>
        internal static string oth {
            get {
                return ResourceManager.GetString("oth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pistolets.
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carabines.
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Jante à Rabais.
        /// </summary>
        internal static string rebrim {
            get {
                return ResourceManager.GetString("rebrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sans monture.
        /// </summary>
        internal static string rimless {
            get {
                return ResourceManager.GetString("rimless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rimmed.
        /// </summary>
        internal static string rimmed {
            get {
                return ResourceManager.GetString("rimmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fusils de chasse.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Semi-Cerclée.
        /// </summary>
        internal static string semir {
            get {
                return ResourceManager.GetString("semir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Section (mm2).
        /// </summary>
        internal static string sez {
            get {
                return ResourceManager.GetString("sez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Certaines mesures sont indicatives et pas exactement les mêmes que les mesures réelles..
        /// </summary>
        internal static string timg {
            get {
                return ResourceManager.GetString("timg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a tool1 Sélectionnez &quot;g&quot; pour les mesures décimales (g / mm2) ou &quot;gr&quot; pour les mesures impériales (lbs / in2).
        /// </summary>
        internal static string tool1 {
            get {
                return ResourceManager.GetString("tool1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Traceur.
        /// </summary>
        internal static string Tra {
            get {
                return ResourceManager.GetString("Tra", resourceCulture);
            }
        }
    }
}
